Crime Analytics

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("../data/raw/crimedata_csv_AllNeighbourhoods_AllYears.csv")
df.head()

,TYPE,YEAR,MONTH,DAY,HOUR,MINUTE,HUNDRED_BLOCK,NEIGHBOURHOOD,X,Y
0,Theft from Vehicle,2026,5,29,20,0,24XX BIRCH ST,Fairview,490288.3251,5.456857e+06
1,Theft from Vehicle,2024,5,23,17,0,24XX BONNYVALE AVE,Victoria-Fraserview,495831.7011,5.451588e+06
2,Theft from Vehicle,2025,4,8,0,23,24XX BURRARD ST,Kitsilano,489392.3161,5.456880e+06
3,Theft from Vehicle,2024,2,9,17,0,24XX CAMBIE ST,Fairview,491636.2151,5.456792e+06
4,Theft from Vehicle,2024,9,15,11,0,24XX CAMBIE ST,Fairview,491636.2151,5.456792e+06

In [6]:
df.shape
df.info()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 917009 entries, 0 to 917008
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   TYPE           917009 non-null  str
 1   YEAR           917009 non-null  int64
 2   MONTH          917009 non-null  int64
 3   DAY            917009 non-null  int64
 4   HOUR           917009 non-null  int64
 5   MINUTE         917009 non-null  int64
 6   HUNDRED_BLOCK  916997 non-null  str
 7   NEIGHBOURHOOD  916908 non-null  str
 8   X              916979 non-null  float64
 9   Y              916979 non-null  float64
dtypes: float64(2), int64(5), str(3)
memory usage: 70.0 MB

Index(['TYPE', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE', 'HUNDRED_BLOCK',
       'NEIGHBOURHOOD', 'X', 'Y'],
      dtype='str')

In [7]:
df.isna().sum().sort_values(ascending=False)

NEIGHBOURHOOD    101
X                 30
Y                 30
HUNDRED_BLOCK     12
YEAR               0
TYPE               0
MINUTE             0
HOUR               0
DAY                0
MONTH              0
dtype: int64

In [10]:
# Cleaning variable names
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)
df.head()

,type,year,month,day,hour,minute,hundred_block,neighbourhood,x,y
0,Theft from Vehicle,2026,5,29,20,0,24XX BIRCH ST,Fairview,490288.3251,5.456857e+06
1,Theft from Vehicle,2024,5,23,17,0,24XX BONNYVALE AVE,Victoria-Fraserview,495831.7011,5.451588e+06
2,Theft from Vehicle,2025,4,8,0,23,24XX BURRARD ST,Kitsilano,489392.3161,5.456880e+06
3,Theft from Vehicle,2024,2,9,17,0,24XX CAMBIE ST,Fairview,491636.2151,5.456792e+06
4,Theft from Vehicle,2024,9,15,11,0,24XX CAMBIE ST,Fairview,491636.2151,5.456792e+06